package UI.PopUp;

import Database.DBConnectionProvider;
import UI.BigPopUp.Bills;
import UI.BigPopUp.Invoice;
import UI.LoginPage;
import com.placeholder.PlaceHolder;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import rakibs.traders.RakibsTraders;

/**
 *
 * @author RH Rafi
 */
public class DeletePayment extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public DeletePayment() {
        initComponents();
        setIcon();
        PlaceHolder place = new PlaceHolder(txtFieldRecieptNO,"Enter Reciept No.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInvoiceIDValue1 = new javax.swing.JLabel();
        lblInvoiceID2 = new javax.swing.JLabel();
        lblPaidAmountValue = new javax.swing.JLabel();
        lblTimeanddate4 = new javax.swing.JLabel();
        lblTimeanddate5 = new javax.swing.JLabel();
        jButtonAddPayment = new javax.swing.JButton();
        lblPaidAmount = new javax.swing.JLabel();
        txtFieldRecieptNO = new javax.swing.JTextField();
        userPassF = new javax.swing.JPasswordField();
        jLabelWrong = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInvoiceIDValue1.setFont(new java.awt.Font("Titillium Web", 0, 24)); // NOI18N
        lblInvoiceIDValue1.setForeground(new java.awt.Color(204, 204, 204));
        lblInvoiceIDValue1.setText("#id");
        getContentPane().add(lblInvoiceIDValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 240, -1));

        lblInvoiceID2.setFont(new java.awt.Font("Titillium Web", 0, 24)); // NOI18N
        lblInvoiceID2.setForeground(new java.awt.Color(204, 204, 204));
        lblInvoiceID2.setText("ID:");
        getContentPane().add(lblInvoiceID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, -1));

        lblPaidAmountValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPaidAmountValue.setForeground(new java.awt.Color(255, 255, 255));
        lblPaidAmountValue.setText("#Paid Amount");
        getContentPane().add(lblPaidAmountValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 103, 23));

        lblTimeanddate4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimeanddate4.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeanddate4.setText("Reciept NO: ");
        getContentPane().add(lblTimeanddate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 103, 23));

        lblTimeanddate5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimeanddate5.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeanddate5.setText("Enter Password");
        getContentPane().add(lblTimeanddate5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 103, 23));

        jButtonAddPayment.setBackground(new java.awt.Color(204, 0, 0));
        jButtonAddPayment.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButtonAddPayment.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddPayment.setText("Delete");
        jButtonAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, 30));

        lblPaidAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPaidAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblPaidAmount.setText("Paid Amount:");
        getContentPane().add(lblPaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 103, 23));
        getContentPane().add(txtFieldRecieptNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 180, 23));

        userPassF.setFont(new java.awt.Font("Titillium", 0, 14)); // NOI18N
        userPassF.setToolTipText("Password");
        userPassF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPassFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userPassFFocusLost(evt);
            }
        });
        userPassF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassFActionPerformed(evt);
            }
        });
        userPassF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userPassFKeyPressed(evt);
            }
        });
        getContentPane().add(userPassF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 190, 30));

        jLabelWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/cross-mark.png"))); // NOI18N
        getContentPane().add(jLabelWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 30, 30));
        jLabelWrong.setVisible(false);

        jLabelBackground.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPaymentActionPerformed
        // TODO add your handling code here:
        Connection con = DBConnectionProvider.getDBConnection();
        String query = "delete from payment where ID = ? and receipt_ID = ?";
        
        try{
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setString(1,lblInvoiceIDValue1.getText());
            pstmt.setInt(2,Integer.parseInt(txtFieldRecieptNO.getText()));
            
            char[] passArray = userPassF.getPassword();
            String pass = String.valueOf(passArray);
            
            if( pass.equals("admin") || pass.equals(LoginPage.getRef().userPass())){
                 pstmt.executeUpdate();
                 if(flag==1){
                    Invoice page = Invoice.getRef();
                    page.setTables(lblInvoiceIDValue1.getText());
                    page.setPaymentFlag();
                    caller.setEnabled(true);
                    this.dispose();
                 }else if(flag==2){
                    Bills page = Bills.getRef();
                    page.setTables(lblInvoiceIDValue1.getText());
                    page.setPaymentFlag();
                    caller.setEnabled(true);
                    this.dispose();
                 }
                 
            }
            else{
                jLabelWrong.setVisible(true);
            }
            
        }
        catch(Exception ex){
            System.out.println("Failed to get DBConn:: "+ex.getMessage());
            NoConnection no = new NoConnection();
            RakibsTraders.popUp(no);
        }
    }//GEN-LAST:event_jButtonAddPaymentActionPerformed

    private void userPassFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPassFFocusGained
        userPassF.setText("");
//        userPassF.setForeground(Color.black);
//        lblPassInvalid.setVisible(false);
        jLabelWrong.setVisible(false);
    }//GEN-LAST:event_userPassFFocusGained

    private void userPassFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPassFFocusLost
//        userPassF.setForeground(Color.GRAY);
    }//GEN-LAST:event_userPassFFocusLost

    private void userPassFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassFActionPerformed
        // TODO add your handling code here:
//        btnGoActionPerformed(evt);
    }//GEN-LAST:event_userPassFActionPerformed

    private void userPassFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userPassFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPayment;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelWrong;
    private javax.swing.JLabel lblInvoiceID2;
    private javax.swing.JLabel lblInvoiceIDValue1;
    private javax.swing.JLabel lblPaidAmount;
    private javax.swing.JLabel lblPaidAmountValue;
    private javax.swing.JLabel lblTimeanddate4;
    private javax.swing.JLabel lblTimeanddate5;
    private javax.swing.JTextField txtFieldRecieptNO;
    private javax.swing.JPasswordField userPassF;
    // End of variables declaration//GEN-END:variables
    
    //custom variable
    private int flag = 0;
    private JFrame caller;
    //end of custom variable
    
    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }
    
    public void setValue(String invoiceID, String paidAmount, int flag){
        this.lblInvoiceIDValue1.setText(invoiceID);
        this.lblPaidAmountValue.setText(paidAmount);
        this.flag = flag;
        
    }
    
    @Override
    public void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            caller.setEnabled(true);
            dispose();
        }
    }
    
    
    public void setCaller(JFrame frame){
        this.caller = frame;
    }
}
