package UI.PopUp;

import Database.DBConnectionProvider;
import Others.Functions;
import UI.BigPopUp.Bills;
import UI.BigPopUp.Invoice;
import UI.BigPopUp.VendorList;
import UI.LoginPage;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import rakibs.traders.RakibsTraders;

/**
 *
 * @author RH Rafi
 */
public class EditCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public EditCustomer() {
        initComponents();
        setIcon();
    }
    private void clearField() {
         this.txtFieldCustomerNameValue.setText("");
         this.jLabelCustomerIDValue.setText("");
         this.txtFieldPhone1.setText("");
         this.txtFieldPhone2.setText("");
         this.txtFieldEmail.setText("");
         this.txtFieldAddress.setText("");
       
//         initComboProductID();
    }
     private boolean checkPassword(){
        char[] passArray = userPassF.getPassword();
        String pass = String.valueOf(passArray);

        if( pass.equals("admin") || pass.equals(LoginPage.getRef().userPass())){
            return true;
        }

        jLabelWrong.setVisible(true);    
        return false;
        
    }
     
      private boolean checkField(){
        if(this.txtFieldCustomerNameValue.getText().equals("") || this.txtFieldPhone1.getText().equals("") ){
//            System.err.println(this.txtFieldAmountValue.getText() + " EROR ");
            return true;
        }
        else return false;
    }
    
    public void setData( String customerID, String customerName, String phone1, String phone2, String Address,String Email ){
           this.jLabelCustomerIDValue.setText(customerID);
           this.txtFieldCustomerNameValue.setText(customerName);
           this.txtFieldPhone1.setText(phone1);
           this.txtFieldPhone2.setText(phone1);
           this.txtFieldEmail.setText(Email);
           this.txtFieldAddress.setText(Address);

    }  
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAddPayment1 = new javax.swing.JButton();
        jButtonAddPayment = new javax.swing.JButton();
        lblCustomerID = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        txtFieldCustomerNameValue = new javax.swing.JTextField();
        txtFieldPhone1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        lblPhone2 = new javax.swing.JLabel();
        txtFieldPhone2 = new javax.swing.JTextField();
        txtFieldEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        txtFieldAddress = new javax.swing.JTextField();
        jButtonAddPayment2 = new javax.swing.JButton();
        userPassF = new javax.swing.JPasswordField();
        jLabelWrong = new javax.swing.JLabel();
        lblTimeanddate5 = new javax.swing.JLabel();
        jLabelCustomerIDValue = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        jButtonAddPayment1.setBackground(new java.awt.Color(67, 196, 114));
        jButtonAddPayment1.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButtonAddPayment1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddPayment1.setText("UPDATE");
        jButtonAddPayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPayment1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddPayment.setBackground(new java.awt.Color(255, 0, 0));
        jButtonAddPayment.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButtonAddPayment.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddPayment.setText("DELETE");
        jButtonAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 150, 30));

        lblCustomerID.setFont(new java.awt.Font("Titillium Web", 1, 16)); // NOI18N
        lblCustomerID.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerID.setText("Customer ID:");
        getContentPane().add(lblCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 23));

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setText("Customer Name:");
        getContentPane().add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 23));

        txtFieldCustomerNameValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldCustomerNameValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldCustomerNameValueFocusLost(evt);
            }
        });
        txtFieldCustomerNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCustomerNameValueActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldCustomerNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 370, 23));

        txtFieldPhone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFieldPhone1.setForeground(new java.awt.Color(255, 102, 0));
        txtFieldPhone1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldPhone1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldPhone1FocusLost(evt);
            }
        });
        txtFieldPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPhone1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 370, 23));

        lblPhone1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone1.setText("Phone Number 1:");
        getContentPane().add(lblPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 130, 23));

        lblPhone2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone2.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone2.setText("Phone Number2:");
        getContentPane().add(lblPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 23));

        txtFieldPhone2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldPhone2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldPhone2FocusLost(evt);
            }
        });
        txtFieldPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPhone2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 370, 23));

        txtFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFieldEmail.setForeground(new java.awt.Color(255, 102, 0));
        txtFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldEmailFocusLost(evt);
            }
        });
        txtFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 370, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 102, 0));
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 103, 40));

        lbAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAddress.setForeground(new java.awt.Color(255, 255, 255));
        lbAddress.setText("Address");
        getContentPane().add(lbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 103, 23));

        txtFieldAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldAddressFocusLost(evt);
            }
        });
        txtFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 370, 60));

        jButtonAddPayment2.setBackground(new java.awt.Color(0, 0, 204));
        jButtonAddPayment2.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButtonAddPayment2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddPayment2.setText("UPDATE");
        jButtonAddPayment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPayment2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddPayment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 150, 30));

        userPassF.setFont(new java.awt.Font("Titillium", 0, 14)); // NOI18N
        userPassF.setToolTipText("Password");
        userPassF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPassFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userPassFFocusLost(evt);
            }
        });
        userPassF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassFActionPerformed(evt);
            }
        });
        userPassF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userPassFKeyPressed(evt);
            }
        });
        getContentPane().add(userPassF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 190, 30));

        jLabelWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/cross-mark.png"))); // NOI18N
        getContentPane().add(jLabelWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 30, 30));
        jLabelWrong.setVisible(false);

        lblTimeanddate5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimeanddate5.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeanddate5.setText("Enter Password");
        getContentPane().add(lblTimeanddate5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 103, 23));

        jLabelCustomerIDValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCustomerIDValue.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelCustomerIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 310, 30));

        jLabelBackground.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPaymentActionPerformed
        // TODO add your handling code here:
        
        if(checkPassword() && !checkField() ){
                Connection con = DBConnectionProvider.getDBConnection();
                String query = "DELETE FROM customer WHERE customer_ID = ?";
                
                try{
                    PreparedStatement pstmt = con.prepareStatement(query);
                    pstmt.setString(1,jLabelCustomerIDValue.getText());
                    pstmt.executeUpdate();
                    DataDeleted page = new DataDeleted();
                    page.setMessage("Customer");
                    RakibsTraders.popUp(page);
                    
                }catch(Exception ex){
                    System.out.println("Failed to get DBConn:: "+ex.getMessage());
                    NoConnection no = new NoConnection();
                    RakibsTraders.popUp(no);
                }
                this.caller.setEnabled(true);
                this.dispose();
        }
        else {
            checkPassword page = new checkPassword();
            RakibsTraders.popUp(page);
        }
        
        
    }//GEN-LAST:event_jButtonAddPaymentActionPerformed

    private void txtFieldCustomerNameValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldCustomerNameValueFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFieldCustomerNameValueFocusGained

    private void txtFieldCustomerNameValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldCustomerNameValueFocusLost

    }//GEN-LAST:event_txtFieldCustomerNameValueFocusLost

    private void txtFieldCustomerNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCustomerNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCustomerNameValueActionPerformed

    private void txtFieldPhone1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPhone1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldPhone1FocusGained

    private void txtFieldPhone1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPhone1FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldPhone1FocusLost

    private void txtFieldPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPhone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPhone1ActionPerformed

    private void txtFieldPhone2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPhone2FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldPhone2FocusGained

    private void txtFieldPhone2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPhone2FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldPhone2FocusLost

    private void txtFieldPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPhone2ActionPerformed

    private void txtFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEmailFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldEmailFocusGained

    private void txtFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEmailFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldEmailFocusLost

    private void txtFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmailActionPerformed

    private void txtFieldAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAddressFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldAddressFocusGained

    private void txtFieldAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAddressFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldAddressFocusLost

    private void txtFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAddressActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFieldAddressActionPerformed

    
    
    private void jButtonAddPayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPayment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddPayment1ActionPerformed
    
   
    
   
    private void jButtonAddPayment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPayment2ActionPerformed
        // TODO add your handling code here:
        if( checkPassword() && !checkField() ){
               Connection con = DBConnectionProvider.getDBConnection();
               String query = "UPDATE customer SET customer_name=?, phone_number1 = ?, phone_number2 = ?, mail = ?,address = ?  WHERE  customer_ID = ?";
                

              try{
                PreparedStatement pstmt = con.prepareStatement(query);
                String cus_ID = jLabelCustomerIDValue.getText();
                String cusName = this.txtFieldCustomerNameValue.getText();
                String phone1 = this.txtFieldPhone1.getText();
                String phone2 = this.txtFieldPhone2.getText();
                String email = this.txtFieldEmail.getText();
                String address = this.txtFieldAddress.getText();
         
               
                pstmt.setString(1,cusName);
                pstmt.setString(2,phone1);
                pstmt.setString(3,phone2);
                pstmt.setString(4,email);
                pstmt.setString(5,address);
                pstmt.setString(6,cus_ID);
                pstmt.executeUpdate();
                clearField();
                Updated up = new Updated();
                userPassF.setText("");
                RakibsTraders.popUp(up);
                this.caller.setEnabled(true);
                this.dispose();
                
            }catch(Exception ex){
                Logger.getLogger(EditCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            checkPassword page = new checkPassword();
            RakibsTraders.popUp(page);
        }
        
        
    }//GEN-LAST:event_jButtonAddPayment2ActionPerformed

    private void userPassFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPassFFocusGained
        userPassF.setText("");
        //        userPassF.setForeground(Color.black);
        //        lblPassInvalid.setVisible(false);
        jLabelWrong.setVisible(false);
    }//GEN-LAST:event_userPassFFocusGained

    private void userPassFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPassFFocusLost
        //        userPassF.setForeground(Color.GRAY);
    }//GEN-LAST:event_userPassFFocusLost

    private void userPassFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassFActionPerformed
        // TODO add your handling code here:
        //        btnGoActionPerformed(evt);
    }//GEN-LAST:event_userPassFActionPerformed

    private void userPassFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userPassFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPayment;
    private javax.swing.JButton jButtonAddPayment1;
    private javax.swing.JButton jButtonAddPayment2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCustomerIDValue;
    private javax.swing.JLabel jLabelWrong;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblTimeanddate5;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldCustomerNameValue;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldPhone1;
    private javax.swing.JTextField txtFieldPhone2;
    private javax.swing.JPasswordField userPassF;
    // End of variables declaration//GEN-END:variables
    
    //custom varaible
    private int flag = 0;
    private JFrame caller;
    //end of custom varaible
    
    
    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }
    
    
    
    private String setDateAndTime(){
        SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
        Date d = new Date();
        String datetime = dFormat.format(d);
        return datetime;
    }
    
    public void setCaller(JFrame frame){
        this.caller = frame;
    }
    
    @Override
    public void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                caller.setEnabled(true);
                dispose();
        }
    }
    
}
