package UI;


import Database.DBConnectionProvider;
import Others.Functions;
import UI.BigPopUp.ExpenseHistory;
import UI.BigPopUp.ProductsTable;
import UI.BigPopUp.TodaysExpense;
import UI.BigPopUp.ViewStock;
import UI.PopUp.DeleteProducts;
import UI.PopUp.EditExpense;
import UI.PopUp.EmployeeSalary;
import UI.PopUp.NoConnection;
import UI.PopUp.NoValue;
import UI.PopUp.Save;
import UI.PopUp.Updated;
import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.annotation.Resources.*;
import javax.swing.ImageIcon;
import static jdk.nashorn.internal.objects.NativeString.trim;
import rakibs.traders.RakibsTraders;

/**
 *
 * @author RH Rafi
 */
public class Expenses extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Expenses() {
        initComponents();
        //initComboCompanyName();
        initComboProductID();
        setIcon();
        PlaceHolder place = new PlaceHolder(txtFieldExpenseCategory,"Enter Expense Category");
        PlaceHolder place1 = new PlaceHolder(txtFieldExpenseCategoryOptional,"Enter Optional Expense");
        PlaceHolder place3 = new PlaceHolder(txtFieldAccountValue1," Enter Account Number ");
        PlaceHolder place4 = new PlaceHolder(txtFieldAmountValue," Enter the amount ");
        PlaceHolder place5 = new PlaceHolder(txtFieldNotesValue," External Notes ");
//        setData();
        
        //setTime();
    }
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHome = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnReturnProducts = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        lblExpenses = new javax.swing.JLabel();
        lblExpenseCategory = new javax.swing.JLabel();
        btnExpenses = new javax.swing.JButton();
        txtFieldExpenseCategoryOptional = new javax.swing.JTextField();
        lblExpenseID = new javax.swing.JLabel();
        txtFieldExpenseCategory = new javax.swing.JTextField();
        lblPaymentType = new javax.swing.JLabel();
        txtFieldAmountValue = new javax.swing.JTextField();
        lblAccount1 = new javax.swing.JLabel();
        txtFieldAccountValue1 = new javax.swing.JTextField();
        lblAccount = new javax.swing.JLabel();
        txtFieldNotesValue = new javax.swing.JTextField();
        lbNotes = new javax.swing.JLabel();
        jButtonEmployeeSalary = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        txtFieldDateValue = new javax.swing.JTextField();
        jButtonExpenseHistory = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jTextFieldExpenseID = new javax.swing.JTextField();
        jComboBoxPaymentMethodValue = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jButtonTodaysExpense = new javax.swing.JButton();
        jButtonEditExpense = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Logo.png"))); // NOI18N
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Admin + icon.png"))); // NOI18N
        lblAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
        });
        getContentPane().add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1128, 11, 110, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/DASHBOARD.png"))); // NOI18N
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 200, 88));

        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/BUY.png"))); // NOI18N
        btnBuy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnBuyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnBuyFocusLost(evt);
            }
        });
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuyMouseExited(evt);
            }
        });
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 138, 23));

        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Sell.png"))); // NOI18N
        btnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSellMouseExited(evt);
            }
        });
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        getContentPane().add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 138, 23));

        btnProducts.setBackground(new java.awt.Color(204, 204, 204));
        btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Products.png"))); // NOI18N
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductsMouseExited(evt);
            }
        });
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 138, 23));

        btnStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Stock.png"))); // NOI18N
        btnStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStockMouseExited(evt);
            }
        });
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 138, 23));

        btnReturnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Return Products.png"))); // NOI18N
        btnReturnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReturnProductsMouseExited(evt);
            }
        });
        btnReturnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnProductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 138, 23));

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Reports.png"))); // NOI18N
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
        });
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        getContentPane().add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 138, 23));

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Settings.png"))); // NOI18N
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingsMouseExited(evt);
            }
        });
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 138, 23));

        lblExpenses.setFont(new java.awt.Font("Titillium", 0, 22)); // NOI18N
        lblExpenses.setForeground(new java.awt.Color(67, 196, 114));
        lblExpenses.setText("Expenses");
        getContentPane().add(lblExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 304, 43));

        lblExpenseCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExpenseCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblExpenseCategory.setText("Expense Category :");
        getContentPane().add(lblExpenseCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 130, 23));

        btnExpenses.setBackground(new java.awt.Color(67, 196, 114));
        btnExpenses.setForeground(new java.awt.Color(67, 196, 114));
        btnExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Expenses_G.png"))); // NOI18N
        btnExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExpensesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExpensesMouseExited(evt);
            }
        });
        btnExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpensesActionPerformed(evt);
            }
        });
        getContentPane().add(btnExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 138, 23));

        txtFieldExpenseCategoryOptional.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldExpenseCategoryOptional.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldExpenseCategoryOptionalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldExpenseCategoryOptionalFocusLost(evt);
            }
        });
        txtFieldExpenseCategoryOptional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldExpenseCategoryOptionalActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldExpenseCategoryOptional, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 370, 23));

        lblExpenseID.setFont(new java.awt.Font("Titillium Web", 1, 16)); // NOI18N
        lblExpenseID.setForeground(new java.awt.Color(255, 255, 255));
        lblExpenseID.setText("Expense ID:");
        getContentPane().add(lblExpenseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 110, 23));

        txtFieldExpenseCategory.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldExpenseCategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldExpenseCategoryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldExpenseCategoryFocusLost(evt);
            }
        });
        txtFieldExpenseCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldExpenseCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldExpenseCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 370, 23));

        lblPaymentType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPaymentType.setForeground(new java.awt.Color(255, 255, 255));
        lblPaymentType.setText("Payment Type:");
        getContentPane().add(lblPaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 103, 23));

        txtFieldAmountValue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtFieldAmountValue.setForeground(new java.awt.Color(255, 102, 0));
        txtFieldAmountValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldAmountValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldAmountValueFocusLost(evt);
            }
        });
        txtFieldAmountValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAmountValueActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldAmountValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 370, 40));

        lblAccount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAccount1.setForeground(new java.awt.Color(255, 102, 0));
        lblAccount1.setText("Amount:");
        getContentPane().add(lblAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 103, 40));

        txtFieldAccountValue1.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldAccountValue1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldAccountValue1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldAccountValue1FocusLost(evt);
            }
        });
        txtFieldAccountValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAccountValue1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldAccountValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 370, 23));

        lblAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setText("Account:");
        getContentPane().add(lblAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 103, 23));

        txtFieldNotesValue.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldNotesValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldNotesValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldNotesValueFocusLost(evt);
            }
        });
        txtFieldNotesValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNotesValueActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldNotesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 370, 60));

        lbNotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNotes.setForeground(new java.awt.Color(255, 255, 255));
        lbNotes.setText("Notes:");
        getContentPane().add(lbNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 103, 23));

        jButtonEmployeeSalary.setBackground(new java.awt.Color(153, 153, 0));
        jButtonEmployeeSalary.setFont(new java.awt.Font("Titillium", 1, 13)); // NOI18N
        jButtonEmployeeSalary.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployeeSalary.setText("EMPLOYEE SALARY");
        jButtonEmployeeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEmployeeSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 170, 30));

        lblDate.setFont(new java.awt.Font("Titillium Web", 1, 16)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, 23));

        txtFieldDateValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldDateValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDateValueFocusLost(evt);
            }
        });
        txtFieldDateValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDateValueActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldDateValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 170, 23));

        jButtonExpenseHistory.setBackground(new java.awt.Color(0, 51, 153));
        jButtonExpenseHistory.setFont(new java.awt.Font("Titillium", 1, 13)); // NOI18N
        jButtonExpenseHistory.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExpenseHistory.setText("EXPENSE HISTORY");
        jButtonExpenseHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpenseHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExpenseHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 170, 30));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Time: ");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 230, 30));

        jTextFieldExpenseID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextFieldExpenseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 220, -1));

        jComboBoxPaymentMethodValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque", "Bank", "Others" }));
        getContentPane().add(jComboBoxPaymentMethodValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 370, -1));

        btnSave.setBackground(new java.awt.Color(67, 196, 114));
        btnSave.setFont(new java.awt.Font("Titillium", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 453, 120, 30));

        jButtonTodaysExpense.setBackground(new java.awt.Color(0, 51, 153));
        jButtonTodaysExpense.setFont(new java.awt.Font("Titillium", 1, 13)); // NOI18N
        jButtonTodaysExpense.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTodaysExpense.setText("TODAYS EXPENSE");
        jButtonTodaysExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodaysExpenseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTodaysExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 170, 30));

        jButtonEditExpense.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditExpense.setFont(new java.awt.Font("Titillium", 1, 13)); // NOI18N
        jButtonEditExpense.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditExpense.setText("EDIT EXPENSE");
        jButtonEditExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditExpenseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 170, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1280, 669));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        
        Sell page = Sell.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        // TODO add your handling code here:
        Functions.logoutLog();
        LoginPage page = LoginPage.getRef();
        page.clearField();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_lblAdminMouseClicked

    private void btnBuyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnBuyFocusGained
        // TODO add your handling code here:      
    }//GEN-LAST:event_btnBuyFocusGained

    private void btnBuyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnBuyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyFocusLost

    private void btnBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseEntered
        // will change to green picture:
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/BUY_G.png")));
    }//GEN-LAST:event_btnBuyMouseEntered

    private void btnBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseExited
        // will change to white picture:
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/BUY.png")));
    }//GEN-LAST:event_btnBuyMouseExited

    private void btnSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseEntered
        // gren:
        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Sell_G.png")));
    }//GEN-LAST:event_btnSellMouseEntered

    private void btnSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseExited
        // white:
        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Sell.png")));
    }//GEN-LAST:event_btnSellMouseExited

    private void btnStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseEntered
        // green
        btnStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Stock_G.png")));
    }//GEN-LAST:event_btnStockMouseEntered

    private void btnStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseExited
        // white:
        btnStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Stock.png")));
    }//GEN-LAST:event_btnStockMouseExited

    private void btnReturnProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnProductsMouseEntered
        // green:
        btnReturnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Return Products_G.png")));
    }//GEN-LAST:event_btnReturnProductsMouseEntered

    private void btnReturnProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnProductsMouseExited
        // white:
        btnReturnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Return Products.png")));
    }//GEN-LAST:event_btnReturnProductsMouseExited

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        // green:
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Reports_G.png")));
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        // white:
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Reports.png")));
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseEntered
        // Green:
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Settings_G.png")));
    }//GEN-LAST:event_btnSettingsMouseEntered

    private void btnSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseExited
        // White:
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Settings.png")));
    }//GEN-LAST:event_btnSettingsMouseExited

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
        Settings page = Settings.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnReturnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnProductsActionPerformed
        // TODO add your handling code here:
        ReturnProducts page = ReturnProducts.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnReturnProductsActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        Sell page = Sell.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        Buy page = Buy.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        Stock page = Stock.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnExpensesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpensesMouseEntered
        // Green:
        btnExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Expenses_G.png")));
    }//GEN-LAST:event_btnExpensesMouseEntered

    private void btnExpensesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpensesMouseExited
        // White:
//        btnExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Expenses.png")));
    }//GEN-LAST:event_btnExpensesMouseExited

    private void btnExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpensesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpensesActionPerformed

    private void btnProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseEntered
        // TODO add your handling code here:
        // btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Products_G.png")));
         btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Products_G.png")));
        
    }//GEN-LAST:event_btnProductsMouseEntered
    private boolean checkField(){
        
        if(this.txtFieldExpenseCategory.getText().equals("") || this.txtFieldAmountValue.getText().equals("") ){
//            System.err.println(this.txtFieldAmountValue.getText() + " EROR ");
            return true;
        }
        else return false;
    }
    private void btnProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseExited
        // TODO add your handling code here:
          btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Products.png")));
    }//GEN-LAST:event_btnProductsMouseExited

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
           // TODO add your handling code here:
           Products page = Products.getRef();
           page.setFlagTime();
           page.setTime();
           this.setFlagTime();
           RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseClicked
        // TODO add your handling code here:
        Products page = Products.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnProductsMouseClicked

    private void txtFieldExpenseCategoryOptionalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldExpenseCategoryOptionalFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFieldExpenseCategoryOptionalFocusGained

    private void txtFieldExpenseCategoryOptionalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldExpenseCategoryOptionalFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFieldExpenseCategoryOptionalFocusLost

    private void txtFieldExpenseCategoryOptionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldExpenseCategoryOptionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldExpenseCategoryOptionalActionPerformed

    private void txtFieldExpenseCategoryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldExpenseCategoryFocusGained
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date d = new Date();
        String date = dFormat.format(d);
        
        if(txtFieldDateValue.getText().equals("")){
            Calendar cal = new GregorianCalendar();
            Integer sec = cal.get(Calendar.SECOND);
            Integer hour = cal.get(Calendar.HOUR);
            if(hour==0)
                hour=12;
            Integer min = cal.get(Calendar.MINUTE);
            Integer am_pm = cal.get(Calendar.AM_PM);
            if(am_pm == 0){
                String timeAndDate = hour + ":" + min + ":" + sec + " " + "AM" + " " + date;
                txtFieldDateValue.setText(timeAndDate);
            }else {
                String timeAndDate = hour + ":" + min + ":" + sec + " " + "PM" + " " + date;
                txtFieldDateValue.setText(timeAndDate);
            }
        }
        String id = Functions.expIDGenerator(date);
        jTextFieldExpenseID.setText(id);
        
    }//GEN-LAST:event_txtFieldExpenseCategoryFocusGained

    private void txtFieldExpenseCategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldExpenseCategoryFocusLost
        
    }//GEN-LAST:event_txtFieldExpenseCategoryFocusLost

    private void txtFieldExpenseCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldExpenseCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldExpenseCategoryActionPerformed

    private void txtFieldAmountValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAmountValueFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtFieldAmountValueFocusGained

    private void txtFieldAmountValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAmountValueFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtFieldAmountValueFocusLost

    private void txtFieldAmountValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAmountValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAmountValueActionPerformed

    private void txtFieldAccountValue1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAccountValue1FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFieldAccountValue1FocusGained

    private void txtFieldAccountValue1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAccountValue1FocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFieldAccountValue1FocusLost

    private void txtFieldAccountValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAccountValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAccountValue1ActionPerformed

    private void txtFieldNotesValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNotesValueFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFieldNotesValueFocusGained

    private void txtFieldNotesValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNotesValueFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFieldNotesValueFocusLost

    private void txtFieldNotesValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNotesValueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFieldNotesValueActionPerformed

    private void jButtonEmployeeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeSalaryActionPerformed
        // TODO add your handling code here:
       if(this.access == 1 || this.access == 2){
            EmployeeSalary page = new EmployeeSalary();
            page.setCaller(this);
            RakibsTraders.popUp(page);
            this.setEnabled(false); 
       }
       

    }//GEN-LAST:event_jButtonEmployeeSalaryActionPerformed

    private void txtFieldDateValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDateValueFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFieldDateValueFocusGained

    private void txtFieldDateValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDateValueFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtFieldDateValueFocusLost

    private void txtFieldDateValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDateValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDateValueActionPerformed

    private void jButtonExpenseHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpenseHistoryActionPerformed
        // TODO add your handling code here:
        // Add all expense history with Expense ID, date, and with other attributes.
        ExpenseHistory page = new ExpenseHistory();
        page.setCaller(this);
        RakibsTraders.bigPopUp(page);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonExpenseHistoryActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        Reports page = Reports.getRef();
        page.setFlagTime();
        page.setTime();
        this.setFlagTime();
        RakibsTraders.changeFrame(this, page);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void jButtonTodaysExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodaysExpenseActionPerformed
        // TODO add your handling code here:
        TodaysExpense page = new TodaysExpense();
        page.setCaller(this);
        RakibsTraders.bigPopUp(page);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonTodaysExpenseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(checkField()){
            NoValue page = new NoValue();
            RakibsTraders.popUp(page);
        }else {
            Connection con = DBConnectionProvider.getDBConnection();
            String query = "INSERT INTO `expenses` (`exp_ID`, `date`, `time`, `category`, `optional_category`, `amount`, `payment_type`, `account`, `notes`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            //            System.err.println("testme");
            String dateAndTime = txtFieldDateValue.getText();
            String time = dateAndTime.substring(0,dateAndTime.indexOf(" ")+3);
            String date = dateAndTime.substring(dateAndTime.indexOf(" ") + 4);
            Double amount = Double.parseDouble(this.txtFieldAmountValue.getText());

            try{
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, jTextFieldExpenseID.getText());
                String[] splitDate = date.split("/");
                date = trim(splitDate[2]) + "-" + trim(splitDate[1]) + "-" + trim(splitDate[0]);
                pstmt.setString(2, date);
                pstmt.setString(3, time);
                pstmt.setString(4, txtFieldExpenseCategory.getText());
                pstmt.setString(5, txtFieldExpenseCategoryOptional.getText());
                pstmt.setDouble(6, amount);
                pstmt.setString(7, jComboBoxPaymentMethodValue.getSelectedItem().toString());
                pstmt.setString(8, txtFieldAccountValue1.getText());
                pstmt.setString(9, txtFieldNotesValue.getText());

                if(jTextFieldExpenseID.getText().equals("0"))
                throw new Exception("Expense ID null");
                else{
                    pstmt.executeUpdate();
                    Save sv = new Save();
                    RakibsTraders.popUp(sv);
                    clearField();
                }
            } catch(Exception ex){
                System.out.println("Failed to get DBConn:: "+ex.getMessage());
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButtonEditExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditExpenseActionPerformed
        // TODO add your handling code here:
        EditExpense page = new EditExpense();
        page.setCaller(this);
        RakibsTraders.popUp(page);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonEditExpenseActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnExpenses;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReturnProducts;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton jButtonEditExpense;
    private javax.swing.JButton jButtonEmployeeSalary;
    private javax.swing.JButton jButtonExpenseHistory;
    private javax.swing.JButton jButtonTodaysExpense;
    private javax.swing.JComboBox<String> jComboBoxPaymentMethodValue;
    private javax.swing.JTextField jTextFieldExpenseID;
    private javax.swing.JLabel lbNotes;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAccount1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExpenseCategory;
    private javax.swing.JLabel lblExpenseID;
    private javax.swing.JLabel lblExpenses;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblPaymentType;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFieldAccountValue1;
    private javax.swing.JTextField txtFieldAmountValue;
    private javax.swing.JTextField txtFieldDateValue;
    private javax.swing.JTextField txtFieldExpenseCategory;
    private javax.swing.JTextField txtFieldExpenseCategoryOptional;
    private javax.swing.JTextField txtFieldNotesValue;
    // End of variables declaration//GEN-END:variables

    //custome variables declaration
    private ArrayList<String> productID = new ArrayList<>();
    private ArrayList<String> companyName = new ArrayList<>();
    private ArrayList<String> model = new ArrayList<>();
    private ArrayList<String> dimension = new ArrayList<>();
    private static Expenses ref;
    private Integer flagTime = 0;
    private Integer access = 0;
    //end custom varibles
    
    public static Expenses getRef(){
        if(ref==null)
            ref = new Expenses();
        return ref;
    }
    
    public void setAcsess(Integer acc){
        this.access = acc;
    }
    
    private void clearField() {
         this.txtFieldDateValue.setText("");
         this.jTextFieldExpenseID.setText("");
         this.txtFieldExpenseCategory.setText("");
         this.txtFieldExpenseCategoryOptional.setText("");
         this.txtFieldAccountValue1.setText("");
         this.txtFieldAmountValue.setText("");
         this.txtFieldNotesValue.setText("");
//         initComboProductID();
    }
    
    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }
    
   public void setFlagTime(){
        if(flagTime==0)
            flagTime=1;
        else
            flagTime=0;
    }
     
     public void setTime(){
        new Thread(){
            public void run(){
                if(flagTime==1){
                    SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");
                    Date d = new Date();
                    String date = dFormat.format(d);
                    int sec;
                    int hour;
                    int min;
                    int am_pm;
                    while(flagTime==1/* && new GregorianCalendar().get(Calendar.SECOND)!=fsec*/){
                        Calendar cal = new GregorianCalendar();
                        sec = cal.get(Calendar.SECOND);
                        //System.out.println(sec);
                        hour = cal.get(Calendar.HOUR);
                        if(hour==0)
                            hour=12;
                        min = cal.get(Calendar.MINUTE);
                        am_pm = cal.get(Calendar.AM_PM);
                        if(am_pm == 0){
                            String time = "Time: " + hour + " : " + min + " : " + sec + " " + "AM" + " Date: " + date;
                            lblTime.setText(time);
                        }else {
                            String time = "Time: " + hour + " : " + min + " : " + sec + " " + "PM" + " Date: " + date;
                            lblTime.setText(time);
                               }
                        try {
                            sleep(1000);
                        } catch (InterruptedException ex) {
                                Logger.getLogger(Sell.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            
                    }    
                }
            }
        }.start();
    }
    
    private void initComboProductID(){
        productID = Functions.productID();
//        Functions.setupAutoComplete(txtFieldProductID, productID); 
    }
    
    private void initComboCompanyName(){
        companyName = Functions.companyName();
//        Functions.setupAutoComplete(txtFieldCompanyName, companyName); 
    }
    
    private void initComboModel(String companyName){
        model = Functions.model(companyName);
//        Functions.setupAutoComplete(txtFieldModel, model);
    }
    
    private void initComboDimension(String companyName, String model){
        dimension = Functions.dimension(companyName, model);
//        Functions.setupAutoComplete(txtFieldDimension, dimension);
    }
    
    @Override
    public void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            Functions.logoutLog();
            //dispose();
            RakibsTraders.close();
        }
    }
}
