/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BigPopUp;

import Database.DBConnectionProvider;
import Others.Functions;
import UI.Buy;
import UI.PopUp.NoConnection;
import UI.PopUp.Save;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rakibs.traders.RakibsTraders;

/**
 *
 * @author RH Rafi
 */
public class Bills extends javax.swing.JFrame {

    /**
     * Creates new form bills
     */
    public Bills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelContactNo = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelPoint2 = new javax.swing.JLabel();
        scrPaneTable = new javax.swing.JScrollPane();
        jLabelDiscountAmount = new javax.swing.JLabel();
        jLabelDiscount = new javax.swing.JLabel();
        jLabelDiscountPercent = new javax.swing.JLabel();
        jLabelLabour = new javax.swing.JLabel();
        jLabelLabourCost = new javax.swing.JLabel();
        jLabelNetAmount = new javax.swing.JLabel();
        jLabelNetAmountMoney = new javax.swing.JLabel();
        jLabelPaid = new javax.swing.JLabel();
        jLabelPaidAmount = new javax.swing.JLabel();
        jLabelChangeAmount = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jLabelDue = new javax.swing.JLabel();
        jLabelDueAmount = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        lblBillingIDValue = new javax.swing.JLabel();
        lblVendorNameValue = new javax.swing.JLabel();
        lblDateandTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblBillingID1 = new javax.swing.JLabel();
        lblVendorName = new javax.swing.JLabel();
        lblShopName = new javax.swing.JLabel();
        lblShopNameValue = new javax.swing.JLabel();
        lblDealershipValue = new javax.swing.JLabel();
        lblDealerShip = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPhoneValue = new javax.swing.JLabel();
        lblVendorIDvalue = new javax.swing.JLabel();
        lblVendorID = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEmailValue = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelContactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContactNo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContactNo.setText("Contact :");
        getContentPane().add(jLabelContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 290, 50));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 60));

        jLabelPoint2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPoint2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPoint2.setText("Lorem Ipsum");
        getContentPane().add(jLabelPoint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 560, 80));
        getContentPane().add(scrPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 990, 250));

        jLabelDiscountAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDiscountAmount.setText("0.0000");
        getContentPane().add(jLabelDiscountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 120, 20));

        jLabelDiscount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDiscount.setText("Discount(0%):");
        getContentPane().add(jLabelDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 80, 20));

        jLabelDiscountPercent.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDiscountPercent.setText("0.0000");
        getContentPane().add(jLabelDiscountPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 90, 20));

        jLabelLabour.setForeground(new java.awt.Color(204, 204, 204));
        jLabelLabour.setText("Labour:");
        getContentPane().add(jLabelLabour, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 61, 20));

        jLabelLabourCost.setForeground(new java.awt.Color(204, 204, 204));
        jLabelLabourCost.setText("0.0000");
        getContentPane().add(jLabelLabourCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 120, 20));

        jLabelNetAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNetAmount.setText("Net Amount:");
        getContentPane().add(jLabelNetAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, -1, 20));

        jLabelNetAmountMoney.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNetAmountMoney.setText("0.0000");
        getContentPane().add(jLabelNetAmountMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 120, 20));

        jLabelPaid.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPaid.setText("Paid:");
        getContentPane().add(jLabelPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 61, 20));

        jLabelPaidAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPaidAmount.setText("0.0000");
        getContentPane().add(jLabelPaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 120, 20));

        jLabelChangeAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelChangeAmount.setText("0.0000");
        getContentPane().add(jLabelChangeAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 130, 20));

        jLabelChange.setForeground(new java.awt.Color(204, 204, 204));
        jLabelChange.setText("Change:");
        getContentPane().add(jLabelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 61, 20));

        jLabelDue.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDue.setText("Due:");
        getContentPane().add(jLabelDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 61, 20));

        jLabelDueAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDueAmount.setText("0.0000");
        getContentPane().add(jLabelDueAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 110, 20));

        jLabelTotal.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTotal.setText("Total:");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 61, 20));

        lblBillingIDValue.setFont(new java.awt.Font("Titillium Web", 0, 28)); // NOI18N
        lblBillingIDValue.setForeground(new java.awt.Color(204, 204, 204));
        lblBillingIDValue.setText("#id");
        getContentPane().add(lblBillingIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 190, -1));

        lblVendorNameValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblVendorNameValue.setForeground(new java.awt.Color(204, 204, 204));
        lblVendorNameValue.setText("#yeasin ");
        getContentPane().add(lblVendorNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 120, -1));

        lblDateandTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDateandTime.setForeground(new java.awt.Color(204, 204, 204));
        lblDateandTime.setText("Time:");
        getContentPane().add(lblDateandTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 260, 20));

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 150, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save & Print");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 150, 30));

        lblBillingID1.setFont(new java.awt.Font("Titillium Web", 0, 28)); // NOI18N
        lblBillingID1.setForeground(new java.awt.Color(204, 204, 204));
        lblBillingID1.setText("Billing ID:");
        getContentPane().add(lblBillingID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 130, -1));

        lblVendorName.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblVendorName.setForeground(new java.awt.Color(204, 204, 204));
        lblVendorName.setText("Vendor Name: ");
        getContentPane().add(lblVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 100, -1));

        lblShopName.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblShopName.setForeground(new java.awt.Color(204, 204, 204));
        lblShopName.setText("Shop Name: ");
        getContentPane().add(lblShopName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 100, -1));

        lblShopNameValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblShopNameValue.setForeground(new java.awt.Color(204, 204, 204));
        lblShopNameValue.setText("RK traders");
        getContentPane().add(lblShopNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 190, -1));

        lblDealershipValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblDealershipValue.setForeground(new java.awt.Color(204, 204, 204));
        lblDealershipValue.setText("Akij, AK, Lorem");
        getContentPane().add(lblDealershipValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 350, -1));

        lblDealerShip.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblDealerShip.setForeground(new java.awt.Color(204, 204, 204));
        lblDealerShip.setText("Dealerships:");
        getContentPane().add(lblDealerShip, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, -1));

        lblPhone.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(204, 204, 204));
        lblPhone.setText("Phone");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 100, -1));

        lblPhoneValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblPhoneValue.setForeground(new java.awt.Color(204, 204, 204));
        lblPhoneValue.setText("017 - 6360- 3579, 015-1560-6947");
        getContentPane().add(lblPhoneValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 360, -1));

        lblVendorIDvalue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblVendorIDvalue.setForeground(new java.awt.Color(204, 204, 204));
        lblVendorIDvalue.setText("#yeasin 001");
        getContentPane().add(lblVendorIDvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 230, -1));

        lblVendorID.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblVendorID.setForeground(new java.awt.Color(204, 204, 204));
        lblVendorID.setText("ID:");
        getContentPane().add(lblVendorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 60, -1));

        lblEmail.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 204, 204));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 100, -1));

        lblEmailValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblEmailValue.setForeground(new java.awt.Color(204, 204, 204));
        lblEmailValue.setText("ryeashin@gmail.com");
        getContentPane().add(lblEmailValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 210, -1));

        jLabelBackground.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String billingId = lblBillingIDValue.getText();
        String vendorId = lblVendorIDvalue.getText();
        String date = lblDateandTime.getText();
        String year = date.substring(date.lastIndexOf("/")+1);
        String month = date.substring(date.indexOf("/")+1, date.lastIndexOf("/"));
        String date1 = date.substring(date.indexOf("M")+2, date.indexOf("/"));
        String newdate = year + "-" + month + "-" + date1;
        String time = date.substring(date.indexOf(":")+2, date.indexOf("M")-2);
        //System.out.println(newdate);
        //System.out.println(time);
        String due = Double.toString(Double.parseDouble(jLabelDueAmount.getText())/table.getRowCount());
        String productId;
        String buyAmount;
        String unitPrice;
        String total;
        //Integer row = 0;
        for(int i=0; i<table.getRowCount(); i++){
            //System.out.println("inside loop:" +i);
            productId = (String) table.getModel().getValueAt(i,0);
            buyAmount = (String) table.getModel().getValueAt(i,3);
            unitPrice = (String) table.getModel().getValueAt(i,4);
            total = (String) table.getModel().getValueAt(i,5);
            
            Connection con = DBConnectionProvider.getDBConnection();
            String query1 = "INSERT INTO `bills` (`billing_id`, `products_id`, `vendor_id`, `date`, `time`, `unit_price`, `product_qty`, `total`, `bill_due`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            String query2 = "SELECT * FROM stock WHERE products_id = ?";
            String query3 = "UPDATE `stock` SET `left` = ? WHERE `stock`.`products_id` = ?";
            String query4 = "UPDATE `products` SET `purchase_price` = ? WHERE `products`.`products_id` = ?";
            try{
                PreparedStatement pstmt1 = con.prepareStatement(query1);
                PreparedStatement pstmt2 = con.prepareStatement(query2);
                PreparedStatement pstmt3 = con.prepareStatement(query3);
                PreparedStatement pstmt4 = con.prepareStatement(query4);
                pstmt1.setString(1, billingId);
                pstmt1.setString(2, productId);
                pstmt1.setString(3, vendorId);
                pstmt1.setString(4, newdate);
                pstmt1.setString(5, time);
                pstmt1.setString(6, unitPrice);
                pstmt1.setString(7, buyAmount);
                pstmt1.setString(8, total);
                pstmt1.setString(9, due);
                pstmt2.setString(1, productId);
                ResultSet rs = pstmt2.executeQuery();
                String left="0";
                while(rs.next())
                     left = Integer.toString(rs.getInt("left")+ Integer.parseInt(buyAmount));
                pstmt3.setString(1, left);
                pstmt3.setString(2, productId);
                pstmt4.setString(1, unitPrice);
                pstmt4.setString(2, productId);
                pstmt1.executeUpdate();
                pstmt3.executeUpdate();
                pstmt4.executeUpdate();
            } catch(Exception ex){
                System.out.println("Failed to get DBConn:: "+ex.getMessage());
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
        }
        Connection con = DBConnectionProvider.getDBConnection();
        String query5 = "UPDATE `vendors` SET `no_of_bus` = `no_of_bus`+1 WHERE `vendors`.`vendor_id` = ?";
        try {
            PreparedStatement pstmt5 = con.prepareStatement(query5);
            pstmt5.setString(1, vendorId);
            pstmt5.executeUpdate();
        } catch (SQLException ex) {
            System.out.println("Failed to get DBConn:: "+ex.getMessage());
            NoConnection no = new NoConnection();
            RakibsTraders.popUp(no);
        }
        this.dispose();
        Buy page = Buy.getRef();
        page.clearField();
        Save sPage = new Save();
        RakibsTraders.popUp(sPage);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JLabel jLabelChangeAmount;
    private javax.swing.JLabel jLabelContactNo;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelDiscountAmount;
    private javax.swing.JLabel jLabelDiscountPercent;
    private javax.swing.JLabel jLabelDue;
    private javax.swing.JLabel jLabelDueAmount;
    private javax.swing.JLabel jLabelLabour;
    private javax.swing.JLabel jLabelLabourCost;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNetAmount;
    private javax.swing.JLabel jLabelNetAmountMoney;
    private javax.swing.JLabel jLabelPaid;
    private javax.swing.JLabel jLabelPaidAmount;
    private javax.swing.JLabel jLabelPoint2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel lblBillingID1;
    private javax.swing.JLabel lblBillingIDValue;
    private javax.swing.JLabel lblDateandTime;
    private javax.swing.JLabel lblDealerShip;
    private javax.swing.JLabel lblDealershipValue;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailValue;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneValue;
    private javax.swing.JLabel lblShopName;
    private javax.swing.JLabel lblShopNameValue;
    private javax.swing.JLabel lblVendorID;
    private javax.swing.JLabel lblVendorIDvalue;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JLabel lblVendorNameValue;
    private javax.swing.JScrollPane scrPaneTable;
    // End of variables declaration//GEN-END:variables
    
    //custom varaibles
    JTable table = new JTable();
    DefaultTableModel data ;
    //end of custom variables
    
    public void setData(String time, DefaultTableModel newData, String billingId, String vendorId, String total, String discount, String labour, String netAmount, String paid, String change, String due){
        lblDateandTime.setText("Time: "+time);    
        this.data = newData;
        table.setModel(data);
        scrPaneTable.getViewport().add(table);
        lblBillingIDValue.setText(billingId);
        jLabelDiscountAmount.setText(total);
        jLabelDiscount.setText("Discount("+discount+"%)");
        Double amount = (Double.parseDouble(total)*Double.parseDouble(discount))/100;
        jLabelDiscountPercent.setText(""+amount);
        jLabelLabourCost.setText(labour);
        jLabelNetAmountMoney.setText(netAmount);
        jLabelPaidAmount.setText(paid);
        jLabelChangeAmount.setText(change);
        jLabelDueAmount.setText(due);
        lblVendorIDvalue.setText(vendorId);
        setVendorField();
    }
    
    private void setVendorField(){
        Connection con = DBConnectionProvider.getDBConnection();
        String query = "SELECT * FROM vendors WHERE vendor_id = ?";
        try{
            PreparedStatement pstmt = con.prepareStatement(query);
            String vendorID = this.lblVendorIDvalue.getText();
            pstmt.setString(1,vendorID);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
              this.lblVendorNameValue.setText(rs.getString("vendor_name"));
              this.lblPhoneValue.setText(rs.getString("phone1") + ", " + rs.getString("phone2"));
              this.lblEmailValue.setText(rs.getString("email"));
              this.lblShopNameValue.setText(rs.getString("shop_name"));
              this.lblDealershipValue.setText(rs.getString("dealerships"));
            }
        }catch(Exception ex){
            System.out.println("Failed to get DBConn:: "+ex.getMessage());
            NoConnection no = new NoConnection();
            RakibsTraders.popUp(no);
        }
    
    }
    
}
