package UI.BigPopUp;

import Database.DBConnectionProvider;
import UI.PopUp.NoConnection;
import com.placeholder.PlaceHolder;
import java.awt.List;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rakibs.traders.RakibsTraders;

/**
 * Profit report would be like, 
 * For todays profit report it will be show the profit of every sell today. Parameter( Date, Invoice ID, Selling Amount, Profit amount)
 * For Month profit report it will show the profit of every day sell. Parameter( date, profit amount )
 * Same goes for 3 months,6 months and for year. Relation would be months to days, 3 months to months,years to months.
 *
 * 
 * 
 * 
 */
public class HistoryOfReturns extends javax.swing.JFrame {
    /**
     * Creates new form ProductsTable
     */
    
    private String customerID = "";
    
    PlaceHolder place,place2;
    
    public HistoryOfReturns() {
        initComponents();
        initTable();
        setIcon();
        place = new PlaceHolder(jTextFieldSearchProduct,"Search Invoice");
        place2 = new PlaceHolder(jTextFieldSearchInvoice,"Search Invoice");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    DefaultTableModel data = new DefaultTableModel(new String[]{"Invoice ID", "Date", "Time" ,"Original Cash", "Deduction", "Returned Cash"}, 0);
    private void initTable(){
        setData();  
        JTable tables = new JTable();
        tables.setModel(data);
        scrPaneTable2.getViewport().add(tables);
        
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldSearchProduct = new javax.swing.JTextField();
        scrPaneTable2 = new javax.swing.JScrollPane();
        lblReturnedHistory = new javax.swing.JLabel();
        jButtonGO = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonGetHistory = new javax.swing.JButton();
        jTextFieldSearchInvoice = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Search History");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 110, 50));

        jTextFieldSearchProduct.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchProductActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 180, 30));
        getContentPane().add(scrPaneTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 1010, 330));

        lblReturnedHistory.setFont(new java.awt.Font("Titillium", 0, 22)); // NOI18N
        lblReturnedHistory.setForeground(new java.awt.Color(67, 196, 114));
        lblReturnedHistory.setText("Returned History");
        getContentPane().add(lblReturnedHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 304, 43));

        jButtonGO.setBackground(new java.awt.Color(0, 0, 153));
        jButtonGO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonGO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGO.setText("GO");
        jButtonGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 60, 30));

        jButtonRefresh.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefresh.setText("REFRESH");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 110, 30));

        jButtonGetHistory.setBackground(new java.awt.Color(0, 51, 153));
        jButtonGetHistory.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGetHistory.setText("Get History");
        jButtonGetHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGetHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 160, 30));

        jTextFieldSearchInvoice.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldSearchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchInvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSearchInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 180, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -360, 2540, 1380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchProductActionPerformed
        // TODO add your handling code here:
        if( jTextFieldSearchProduct.getText().startsWith("INV#") ){
            getTheSearchDone(jTextFieldSearchProduct.getText());
        }
    }//GEN-LAST:event_jTextFieldSearchProductActionPerformed

    public void getTheSearchDone( String SearchInvoiceID ){
            DefaultTableModel data2 = new DefaultTableModel(new String[]{"Invoice ID", "Date", "Time","Original Cash", "Deduction", "Returned Cash"}, 0);
            data.getDataVector().removeAllElements();
            JTable table2 = new JTable();
            table2.setModel(data2);
            scrPaneTable2.getViewport().add(table2);
            
            Connection con = DBConnectionProvider.getDBConnection();
            String query = "SELECT * from returned_list where invoice_ID = ?";

            try{
                PreparedStatement pstmt2 = con.prepareStatement(query);
                pstmt2.setString( 1,SearchInvoiceID );
                ResultSet rs = pstmt2.executeQuery();

                if(rs.next()){
                    do{ 
                        String col1 = rs.getString("invoice_ID");
                        String col2 = rs.getString("Date");
                        String col3 = rs.getString("Time");
                        String col4 = Double.toString(rs.getDouble("original_total"));
                        String col5 = Double.toString(rs.getDouble("Deduction"));
                        String col6 = Double.toString(rs.getDouble("total_cashBack"));
                        
                        data2.addRow(new Object[]{col1, col2, col3, col4, col5, col6});
                    }while(rs.next());
                    table.setModel(data);
                    rs.close();
                }

            }catch(Exception ex){
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
    }
    
    private void jButtonGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGOActionPerformed
        // TODO add your handling code here:
        String SearchInvoiceID = jTextFieldSearchProduct.getText();
        
         if(SearchInvoiceID.startsWith("INV#")){
             getTheSearchDone(SearchInvoiceID);
        }
        
    }//GEN-LAST:event_jButtonGOActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        data.getDataVector().removeAllElements();
        table.setModel(data);
        scrPaneTable2.getViewport().add(table);
        setData();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonGetHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetHistoryActionPerformed
        // TODO add your handling code here:
        String SearchInvoiceID = jTextFieldSearchInvoice.getText();
        if( SearchInvoiceID.startsWith("INV#") ){
            HistoryReciept page = new HistoryReciept();
            page.setData(SearchInvoiceID, customerID,"0.0",data );
            page.setCaller(this);
            RakibsTraders.bigPopUp(page);
            this.setEnabled(false);
            

        }

    }//GEN-LAST:event_jButtonGetHistoryActionPerformed

    private void jTextFieldSearchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchInvoiceActionPerformed

   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryOfReturns().setVisible(true);
            }
        });
    }
    
    public void setCustomerID( String CusID ){
        this.customerID = CusID;
    }
    
    private void setData(){
        
        
        
        
        Connection con = DBConnectionProvider.getDBConnection();
        String query= "SELECT * from returned_list";
        try{
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery(query);
            if(rs.next()){
                do{
                    String col1 = rs.getString("invoice_ID");
                    String col2 = rs.getString("Date");
                    String col3 = rs.getString("Time");
                    String col4 = Double.toString(rs.getDouble("original_total"));
                    String col5 = Double.toString(rs.getDouble("Deduction"));
                    String col6 = Double.toString(rs.getDouble("total_cashBack"));

                    data.addRow(new Object[]{col1, col2, col3, col4, col5, col6});
                }while(rs.next());
                table.setModel(data);
                rs.close();
            }

        }catch(Exception ex){
            System.out.println("No database connection"+ex);
            NoConnection no = new NoConnection();
            RakibsTraders.popUp(no);
        }
    }

    //custom variable
    private JTable table = new JTable();
    private JFrame caller;
    //end of custom variable
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGO;
    private javax.swing.JButton jButtonGetHistory;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldSearchInvoice;
    private javax.swing.JTextField jTextFieldSearchProduct;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblReturnedHistory;
    private javax.swing.JScrollPane scrPaneTable2;
    // End of variables declaration//GEN-END:variables
   
    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }

    @Override
    public void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            caller.setEnabled(true);
            dispose();
        }
    }
    
    
    public void setCaller(JFrame frame){
        this.caller = frame;
    }
    
}
