package UI.BigPopUp;

import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hasan
 * 
 * 
 */


public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
        setIcon();
    }
     //Rafis legendary of reference
    
//    private static Invoice ref;
//    public static Invoice getRef(){
//        if(ref==null)
//            ref = new Invoice();
//        return ref;
//    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelContactNo = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelPoint2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelDiscountAmount = new javax.swing.JLabel();
        jLabelDiscount = new javax.swing.JLabel();
        jLabelDiscountPercent = new javax.swing.JLabel();
        jLabelLabour = new javax.swing.JLabel();
        jLabelPoint13 = new javax.swing.JLabel();
        jLabelNetAmount = new javax.swing.JLabel();
        jLabelNetAmountMoney = new javax.swing.JLabel();
        jLabelPaid = new javax.swing.JLabel();
        jLabelPaidAmount = new javax.swing.JLabel();
        jLabelChangeAmount = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jLabelDue = new javax.swing.JLabel();
        jLabelDueAmount = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        lblInvoiceIDValue = new javax.swing.JLabel();
        lblInvoiceID = new javax.swing.JLabel();
        lblDateandTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerNameValue = new javax.swing.JLabel();
        lbCustomerID = new javax.swing.JLabel();
        lblCustomerIDvalue = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPhoneValue = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEmailValue = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelContactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContactNo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContactNo.setText("Contact :");
        getContentPane().add(jLabelContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 290, 50));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 60));

        jLabelPoint2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPoint2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPoint2.setText("Lorem Ipsum");
        getContentPane().add(jLabelPoint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 560, 80));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 990, 250));

        jLabelDiscountAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDiscountAmount.setText("0.0000");
        getContentPane().add(jLabelDiscountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 120, 20));

        jLabelDiscount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDiscount.setText("Discount(0%):");
        getContentPane().add(jLabelDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 80, 20));

        jLabelDiscountPercent.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDiscountPercent.setText("0.0000");
        getContentPane().add(jLabelDiscountPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, 90, 20));

        jLabelLabour.setForeground(new java.awt.Color(204, 204, 204));
        jLabelLabour.setText("Labour:");
        getContentPane().add(jLabelLabour, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 61, 20));

        jLabelPoint13.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPoint13.setText("0.0000");
        getContentPane().add(jLabelPoint13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 120, 20));

        jLabelNetAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNetAmount.setText("Net Amount:");
        getContentPane().add(jLabelNetAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, -1, 20));

        jLabelNetAmountMoney.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNetAmountMoney.setText("0.0000");
        getContentPane().add(jLabelNetAmountMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 120, 20));

        jLabelPaid.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPaid.setText("Paid:");
        getContentPane().add(jLabelPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 61, 20));

        jLabelPaidAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPaidAmount.setText("0.0000");
        getContentPane().add(jLabelPaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 120, 20));

        jLabelChangeAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelChangeAmount.setText("0.0000");
        getContentPane().add(jLabelChangeAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 130, 20));

        jLabelChange.setForeground(new java.awt.Color(204, 204, 204));
        jLabelChange.setText("Change:");
        getContentPane().add(jLabelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 61, 20));

        jLabelDue.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDue.setText("Due:");
        getContentPane().add(jLabelDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 61, 20));

        jLabelDueAmount.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDueAmount.setText("0.0000");
        getContentPane().add(jLabelDueAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 110, 20));

        jLabelTotal.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTotal.setText("Total:");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 61, 20));

        lblInvoiceIDValue.setFont(new java.awt.Font("Titillium Web", 0, 28)); // NOI18N
        lblInvoiceIDValue.setForeground(new java.awt.Color(204, 204, 204));
        lblInvoiceIDValue.setText("#id");
        getContentPane().add(lblInvoiceIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 190, -1));

        lblInvoiceID.setFont(new java.awt.Font("Titillium Web", 0, 28)); // NOI18N
        lblInvoiceID.setForeground(new java.awt.Color(204, 204, 204));
        lblInvoiceID.setText("Invoice ID:");
        getContentPane().add(lblInvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 170, -1));

        lblDateandTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDateandTime.setForeground(new java.awt.Color(204, 204, 204));
        lblDateandTime.setText("Time:");
        getContentPane().add(lblDateandTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 260, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Returns YES/NO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 150, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save & Print");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 150, 30));

        lblCustomerName.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(204, 204, 204));
        lblCustomerName.setText("Customer Name: ");
        getContentPane().add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, -1));

        lblCustomerNameValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblCustomerNameValue.setForeground(new java.awt.Color(204, 204, 204));
        lblCustomerNameValue.setText("#yeasin ");
        getContentPane().add(lblCustomerNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 250, -1));

        lbCustomerID.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lbCustomerID.setForeground(new java.awt.Color(204, 204, 204));
        lbCustomerID.setText("Customer ID:");
        getContentPane().add(lbCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 100, -1));

        lblCustomerIDvalue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblCustomerIDvalue.setForeground(new java.awt.Color(204, 204, 204));
        lblCustomerIDvalue.setText("#yeasin 001");
        getContentPane().add(lblCustomerIDvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 230, -1));

        lblPhone.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(204, 204, 204));
        lblPhone.setText("Phone");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 30));

        lblPhoneValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblPhoneValue.setForeground(new java.awt.Color(204, 204, 204));
        lblPhoneValue.setText("017 - 6360- 3579, 015-1560-6947");
        getContentPane().add(lblPhoneValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 360, 30));

        lblEmail.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 204, 204));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 100, 30));

        lblEmailValue.setFont(new java.awt.Font("Titillium Web", 0, 15)); // NOI18N
        lblEmailValue.setForeground(new java.awt.Color(204, 204, 204));
        lblEmailValue.setText("ryeashin@gmail.com");
        getContentPane().add(lblEmailValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 210, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Titillium Web", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 150, 30));

        jLabelBackground.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JLabel jLabelChangeAmount;
    private javax.swing.JLabel jLabelContactNo;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelDiscountAmount;
    private javax.swing.JLabel jLabelDiscountPercent;
    private javax.swing.JLabel jLabelDue;
    private javax.swing.JLabel jLabelDueAmount;
    private javax.swing.JLabel jLabelLabour;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNetAmount;
    private javax.swing.JLabel jLabelNetAmountMoney;
    private javax.swing.JLabel jLabelPaid;
    private javax.swing.JLabel jLabelPaidAmount;
    private javax.swing.JLabel jLabelPoint13;
    private javax.swing.JLabel jLabelPoint2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCustomerID;
    private javax.swing.JLabel lblCustomerIDvalue;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerNameValue;
    private javax.swing.JLabel lblDateandTime;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailValue;
    private javax.swing.JLabel lblInvoiceID;
    private javax.swing.JLabel lblInvoiceIDValue;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneValue;
    // End of variables declaration//GEN-END:variables


    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }
    
}
