package UI.BigPopUp;

import Database.DBConnectionProvider;
import UI.PopUp.NoConnection;
import UI.PopUp.NoValue;
import UI.Reports;
import UI.ReturnProducts;
import com.placeholder.PlaceHolder;
import java.awt.List;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rakibs.traders.RakibsTraders;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 * Profit report would be like, 
 * For todays profit report it will be show the profit of every sell today. Parameter( Date, Invoice ID, Selling Amount, Profit amount)
 * For Month profit report it will show the profit of every day sell. Parameter( date, profit amount )
 * Same goes for 3 months,6 months and for year. Relation would be months to days, 3 months to months,years to months.
 *
 * 
 * 
 * 
 */
public class InvoiceList extends javax.swing.JFrame {
    /**
     * Creates new form ProductsTable
     */
    PlaceHolder place;
    
    public InvoiceList() {
        initComponents();
        initTable();
        setIcon();
        place = new PlaceHolder(jTextFieldSearchInvoice,"Enter Invoice ID");
        place = new PlaceHolder(jTextFieldSearchProduct1,"Search Invoice");
        ref=this;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldSearchInvoice = new javax.swing.JTextField();
        scrPaneTable2 = new javax.swing.JScrollPane();
        lblInvoiceList = new javax.swing.JLabel();
        jTextFieldSearchProduct1 = new javax.swing.JTextField();
        jButtonViewStock = new javax.swing.JButton();
        jButtonGO = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Search Invoice");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 110, 50));

        jTextFieldSearchInvoice.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldSearchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchInvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSearchInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 180, 30));
        getContentPane().add(scrPaneTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 980, 310));

        lblInvoiceList.setFont(new java.awt.Font("Titillium", 0, 22)); // NOI18N
        lblInvoiceList.setForeground(new java.awt.Color(67, 196, 114));
        lblInvoiceList.setText("Invoice List");
        getContentPane().add(lblInvoiceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 304, 43));

        jTextFieldSearchProduct1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldSearchProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchProduct1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSearchProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 180, 30));

        jButtonViewStock.setBackground(new java.awt.Color(0, 51, 153));
        jButtonViewStock.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewStock.setText("Get Invoice");
        jButtonViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewStockActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 160, 30));

        jButtonGO.setBackground(new java.awt.Color(0, 0, 153));
        jButtonGO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonGO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGO.setText("GO");
        jButtonGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 60, 30));

        jButtonRefresh.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefresh.setText("REFRESH");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 110, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -360, 2540, 1380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchInvoiceActionPerformed

    private void jTextFieldSearchProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchProduct1ActionPerformed
        // TODO add your handling code here:
        getTheSearchDone();
    }//GEN-LAST:event_jTextFieldSearchProduct1ActionPerformed

    private JTable productTable = new JTable();
    
    private void jButtonViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewStockActionPerformed
        // TODO add your handling code here:
        String SearchInvoiceID = jTextFieldSearchInvoice.getText();
        if( SearchInvoiceID.startsWith("INV#") ){
            Invoice page = Invoice.getRef();
            page.setCaller(this);
            page.AccessSave = true;
            DefaultTableModel data = new DefaultTableModel(new String[]{"Products ID", "Company Name", "Model", "BOX", "PCS", "FEET", "Unit", "Unit Price", "Total"}, 0);

            Connection con = DBConnectionProvider.getDBConnection();

            String query1 = "Select * from invoice_list where invoice_ID = ?";
            String query2 = "Select * from invoice_products where invoice_ID = ?";
            String query3 = "Select * from payment where invoice_ID = ?";
            String query4 = "Select * from products where products_ID = ?";
            String query5 = "select sum(paid_amount) as total_paid_amount from payment where ID = ?";

            String timeAndDate="",customerID="",PayableNumber;
            double databaseTotal = 0.0; 
            PreparedStatement pstmt;
            Double totalPrice = 0.0, totalPaidForInvoice = 0.0 , Discount = 0.0 , LabourCost=0.0 ;

            try {
                pstmt = con.prepareStatement(query1);
                pstmt.setString(1,SearchInvoiceID);
                ResultSet rs = pstmt.executeQuery();

                while(rs.next()){
                    timeAndDate = rs.getString("time") + rs.getString("date");
                    customerID = rs.getString("customer_ID");
                    //totalPrice = rs.getDouble("total");
                    LabourCost = rs.getDouble("labour_cost");
                    Discount = rs.getDouble("discount");
                    databaseTotal = rs.getDouble("total");
                }

            } catch (SQLException ex) {
    //            Logger.getLogger(InvoiceList.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }

            String productID = "",companyName="", ItemUnit = "",model = "", buyAmount = "";
            Double unitPrice=0.0, TotalForSingleRow = 0.0 ;
            String Box = "", Pcs = "", Feet = "";
            
            try {
                pstmt = con.prepareStatement(query2);
                pstmt.setString(1,SearchInvoiceID);
                ResultSet rs = pstmt.executeQuery();
                PreparedStatement pstmt2 = con.prepareStatement(query4);

                while( rs.next() ){
                       productID = rs.getString("product_ID");
                       TotalForSingleRow = rs.getDouble("price");
                       Box = rs.getString("Box");
                       Pcs = rs.getString("Pcs");
                       Feet = rs.getString("feet");
                       
                       pstmt2.setString(1,productID);
                       ResultSet rs2 = pstmt2.executeQuery();

                       while( rs2.next() ) {
                           companyName = rs2.getString("company_name");
                           model = rs2.getString("model");
                           ItemUnit = rs2.getString("item_unit");
                       }
                       
                       if( ItemUnit.equals("Pcs") || ItemUnit.equals("pcs") || ItemUnit.equals("PCS") )
                            buyAmount = rs.getString("Pcs");
                       else if( ItemUnit.equals("Box") || ItemUnit.equals("box") || ItemUnit.equals("BOX") ) 
                           buyAmount = rs.getString("Box");
                       else 
                           buyAmount = rs.getString("feet");
                           
                       if( Double.parseDouble( buyAmount )  > 0 ){
                           try{
                               unitPrice = TotalForSingleRow/(Double.parseDouble(buyAmount) );
                           }catch(Exception ex){
                               System.out.println("Exception parse: "+ex);
                           }
                            
                        }
                       String modify = String.format( "%.4f",unitPrice ); // Truncating the value
                       unitPrice = Double.parseDouble(modify);
                       
                       System.err.println( Box + " " + Pcs + " " + Feet + " " + ItemUnit + " " + buyAmount + " " + unitPrice );
                       
                       data.addRow(new Object[]{productID,companyName,model, Box, Pcs, Feet, ItemUnit, unitPrice, TotalForSingleRow});
                }

            } catch (SQLException ex) {
    //            Logger.getLogger(InvoiceList.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
            try {
                pstmt = con.prepareStatement(query5);
                pstmt.setString(1,SearchInvoiceID);
                ResultSet rs = pstmt.executeQuery();

                while( rs.next() ){
                    totalPaidForInvoice = rs.getDouble("total_paid_amount"); 
                }
                rs.close();

            } catch (SQLException ex) {
                Logger.getLogger(InvoiceList.class.getName()).log(Level.SEVERE, null, ex);
            }
            Integer row=0;
            for(int i=0; i<data.getRowCount(); i++)
                totalPrice+= (Double) data.getValueAt(row++,8);
            double netPay = totalPrice + LabourCost - Discount;
            
            Double DeductedAmountOfReturnedProduct = 0.0;
            if( Math.abs(netPay-databaseTotal) > 0 ){
                DeductedAmountOfReturnedProduct = Math.abs(netPay-databaseTotal);
            }
            netPay = netPay + DeductedAmountOfReturnedProduct;
            page.setDedctVal(DeductedAmountOfReturnedProduct);
            
            page.setData(timeAndDate,SearchInvoiceID, customerID, Double.toString(totalPrice), Double.toString( Discount ), Double.toString(LabourCost), Double.toString(netPay), data);
            if(!"Enter Invoice ID".equals(jTextFieldSearchInvoice.getText()) ){ 
                page.setTables(jTextFieldSearchInvoice.getText());
                RakibsTraders.bigPopUp(page); 
                this.setEnabled(false);
            }else{
                NoValue n_page = new NoValue();
                n_page.setCaller(this);
                RakibsTraders.popUp(n_page);
                jTextFieldSearchInvoice.setText("");
                this.setEnabled(false);
            }
        
        }
       
        
        
    }//GEN-LAST:event_jButtonViewStockActionPerformed

    private void jButtonGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGOActionPerformed
        // TODO add your handling code here:
        String SearchInvoiceID = jTextFieldSearchProduct1.getText();
        
        if(SearchInvoiceID.startsWith("INV#")){
            data.getDataVector().removeAllElements();
            table.setModel(data);
            scrPaneTable2.getViewport().add(table);

            
            Connection con = DBConnectionProvider.getDBConnection();
            String query = "select * from invoice_list where invoice_ID = ?";
            String query2 = "select sum(paid_amount) as total_paid_amount from payment where ID = ?";

            try{
                PreparedStatement pstmt2 = con.prepareStatement(query);
                pstmt2.setString( 1,SearchInvoiceID );
                ResultSet rs = pstmt2.executeQuery();

                PreparedStatement pstmt = con.prepareStatement(query2);

                if(rs.next()){
                    do{ 
                        String col1 = rs.getString("date");
                        String col2 = rs.getString("time");
                        String col3 = rs.getString("invoice_ID");
                        String col4 = rs.getString("customer_ID");
                        String col5 = Double.toString(rs.getDouble("total"));
                        String col6 = "0.0";
                        pstmt.setString(1,col3);
                        ResultSet rs2 = pstmt.executeQuery();
                        while(rs2.next()){
                            col6 = Double.toString(rs2.getDouble("total_paid_amount"));
                        }
                        Double total_due = (Double.parseDouble(col5)-Double.parseDouble(col6));
                        if( total_due < 0.0 )total_due = 0.0;

                        data.addRow(new Object[]{col1, col2, col3, col4, col5,Double.toString(total_due)});
                    }while(rs.next());
                    table.setModel(data);
                    rs.close();
                }

            }catch(Exception ex){
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
        }
    }//GEN-LAST:event_jButtonGOActionPerformed

    private void getTheSearchDone()
    {
                String SearchInvoiceID = jTextFieldSearchProduct1.getText();
        
        if(SearchInvoiceID.startsWith("INV#")){
            data.getDataVector().removeAllElements();
            table.setModel(data);
            scrPaneTable2.getViewport().add(table);

            
            Connection con = DBConnectionProvider.getDBConnection();
            String query = "select * from invoice_list where invoice_ID = ?";
            String query2 = "select sum(paid_amount) as total_paid_amount from payment where ID = ?";

            try{
                PreparedStatement pstmt2 = con.prepareStatement(query);
                pstmt2.setString( 1,SearchInvoiceID );
                ResultSet rs = pstmt2.executeQuery();

                PreparedStatement pstmt = con.prepareStatement(query2);

                if(rs.next()){
                    do{ 
                        String col1 = rs.getString("date");
                        String col2 = rs.getString("time");
                        String col3 = rs.getString("invoice_ID");
                        String col4 = rs.getString("customer_ID");
                        String col5 = Double.toString(rs.getDouble("total"));
                        String col6 = "0.0";
                        pstmt.setString(1,col3);
                        ResultSet rs2 = pstmt.executeQuery();
                        while(rs2.next()){
                            col6 = Double.toString(rs2.getDouble("total_paid_amount"));
                        }
                        Double total_due = (Double.parseDouble(col5)-Double.parseDouble(col6));
                        if( total_due < 0.0 )total_due = 0.0;

                        data.addRow(new Object[]{col1, col2, col3, col4, col5,Double.toString(total_due)});
                    }while(rs.next());
                    table.setModel(data);
                    rs.close();
                }

            }catch(Exception ex){
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
        }                
    }
    
    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        data.getDataVector().removeAllElements();
        table.setModel(data);
        scrPaneTable2.getViewport().add(table);
        setData();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    
   // */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceList().setVisible(true);
            }
        });
    }
    // No Space Found
    private DefaultTableModel data = new DefaultTableModel(new String[]{"DATE","TIME", "INVOICE ID", "CUSTOMER ID" ,"INV AMOUNT", "DUE" }, 0);
    
    
    private void initTable(){
        setData();  
        JTable tables = new JTable();
        tables.setModel(data);
        scrPaneTable2.getViewport().add(tables);

    }
    
    private void setData(){
        Connection con = DBConnectionProvider.getDBConnection();
        String query = "select * from invoice_list";
        String query2 = "select sum(paid_amount) as total_paid_amount from payment where ID = ?";
        
        try{
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery(query);
            
            PreparedStatement pstmt = con.prepareStatement(query2);
            
            if(rs.next()){
                do{
                    
                    String col1 = rs.getString("date");
                    String col2 = rs.getString("time");
                    String col3 = rs.getString("invoice_ID");
                    String col4 = rs.getString("customer_ID");
                    String col5 = Double.toString(rs.getDouble("total"));
                    String col6 = "0.0";
                    pstmt.setString(1,col3);
                    ResultSet rs2 = pstmt.executeQuery();
                    while(rs2.next()){
                        col6 = Double.toString(rs2.getDouble("total_paid_amount"));
                    }
                    Double total_due = (Double.parseDouble(col5)-Double.parseDouble(col6));
                    if( total_due < 0.0 )total_due = 0.0;
                    
                    data.addRow(new Object[]{col1, col2, col3, col4, col5,Double.toString(total_due)});
                }while(rs.next());
                table.setModel(data);
                rs.close();
            }

        }catch(Exception ex){
            System.out.println("No database connection"+ex);
            NoConnection no = new NoConnection();
            RakibsTraders.popUp(no);
        }
    }

    //custom variable
    private JTable table = new JTable();
    private static InvoiceList ref;
    private JFrame caller;
    //end of custom variable
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGO;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonViewStock;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldSearchInvoice;
    private javax.swing.JTextField jTextFieldSearchProduct1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblInvoiceList;
    private javax.swing.JScrollPane scrPaneTable2;
    // End of variables declaration//GEN-END:variables
   
    
    @Override
    public void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            caller.setEnabled(true);
            dispose();
        }
    }
    
    
    public void setCaller(JFrame frame){
        this.caller = frame;
    }
  
    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }

    public static InvoiceList getRef(){
        if(ref==null)
            ref = new InvoiceList();
        return ref;
    }
    
    
    
}
