package UI.BigPopUp;

import Database.DBConnectionProvider;
import UI.Buy;
import UI.PopUp.NoConnection;
import UI.Products;
import UI.Sell;
import UI.Stock;
import com.placeholder.PlaceHolder;
import java.awt.List;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rakibs.traders.RakibsTraders;

/**
 *
 * @author RH Rafi
 */
public class ProductsTable extends javax.swing.JFrame {

    /**
     * Creates new form ProductsTable
     */
    PlaceHolder place;
    
    public ProductsTable() {
        initComponents();
        initTable();
        setIcon();
        place = new PlaceHolder(jTextFieldSearchProduct,"Enter Product ID");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPaneTable = new javax.swing.JScrollPane();
        lblProductList = new javax.swing.JLabel();
        jTextFieldSearchProduct = new javax.swing.JTextField();
        jButtonGO = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(scrPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1020, 440));

        lblProductList.setFont(new java.awt.Font("Titillium", 0, 22)); // NOI18N
        lblProductList.setForeground(new java.awt.Color(67, 196, 114));
        lblProductList.setText("Product List");
        getContentPane().add(lblProductList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 304, 43));

        jTextFieldSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchProductActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 260, 30));

        jButtonGO.setBackground(new java.awt.Color(0, 0, 153));
        jButtonGO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonGO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGO.setText("GO");
        jButtonGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 60, 30));

        jButtonRefresh.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefresh.setText("REFRESH");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 110, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -360, 2540, 1380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private DefaultTableModel data = new DefaultTableModel(new String[]{"Product ID","MODEL", "Company Name", "Dimension" ,"Pcs Per Box", "Item Unit" ,"Purchase Price","Sell Price"}, 0);
    
    private void getTheSearchDone(){
        String SearchProductID = jTextFieldSearchProduct.getText();
        
        if(SearchProductID.startsWith("#")){
            data.getDataVector().removeAllElements();
            table.setModel(data);
            scrPaneTable.getViewport().add(table);

            
            Connection con = DBConnectionProvider.getDBConnection();
            String query = "select * from products where products_id = ?";

            try{
                PreparedStatement pstmt2 = con.prepareStatement(query);
                pstmt2.setString(1,SearchProductID );
                ResultSet rs = pstmt2.executeQuery();


                if(rs.next()){
                    do{ 
                        String col1 = rs.getString("products_id");
                        String col2 = rs.getString("model");
                        String col3 = rs.getString("company_name");
                        String col4 = rs.getString("dimension");
                        Integer col5 = rs.getInt("pcs_per_box");
                        String col6 = rs.getString("item_unit");
                        String col7 = Double.toString(rs.getDouble("purchase_price"));
                        String col8 = Double.toString(rs.getDouble("selling_price"));
                        
                        data.addRow(new Object[]{col1, col2, col3, col4, col5,col6,col7,col8});
                    }while(rs.next());
                    table.setModel(data);
                    rs.close();
                }

            }catch(Exception ex){
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
        }
        else
        {
            data.getDataVector().removeAllElements();
            table.setModel(data);
            scrPaneTable.getViewport().add(table);

            
            Connection con = DBConnectionProvider.getDBConnection();
            String query = "select * from products where model = ?";

            try{
                PreparedStatement pstmt2 = con.prepareStatement(query);
                pstmt2.setString(1,SearchProductID );
                ResultSet rs = pstmt2.executeQuery();


                if(rs.next()){
                    do{ 
                        String col1 = rs.getString("products_id");
                        String col2 = rs.getString("model");
                        String col3 = rs.getString("company_name");
                        String col4 = rs.getString("dimension");
                        Integer col5 = rs.getInt("pcs_per_box");
                        String col6 = rs.getString("item_unit");
                        String col7 = Double.toString(rs.getDouble("purchase_price"));
                        String col8 = Double.toString(rs.getDouble("selling_price"));
                        
                        data.addRow(new Object[]{col1, col2, col3, col4, col5,col6,col7,col8});
                    }while(rs.next());
                    table.setModel(data);
                    rs.close();
                }

            }catch(Exception ex){
                System.out.println("No database connection"+ex);
                NoConnection no = new NoConnection();
                RakibsTraders.popUp(no);
            }
        }
    }
    
    
    
    private void jButtonGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGOActionPerformed
        // TODO add your handling code here:
           getTheSearchDone();
    }//GEN-LAST:event_jButtonGOActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        data.getDataVector().removeAllElements();
        table.setModel(data);
        scrPaneTable.getViewport().add(table);
        setData();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchProductActionPerformed
        // TODO add your handling code here:
        getTheSearchDone();
        
    }//GEN-LAST:event_jTextFieldSearchProductActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsTable().setVisible(true);
            }
        });
    }

    private void initTable(){
        setData();
        scrPaneTable.getViewport().add(table);
    }
    
    private void setData(){
        DefaultTableModel data = new DefaultTableModel(new String[]{"Products ID", "Company Name", "Model", "Dimension", "Pcs per Box", "Item Unit", "Purchase Price", "Selling price"}, 0);
        Connection con = DBConnectionProvider.getDBConnection();
        String query= "select * from products";
        try{
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery(query);
            if(rs.next()){
                do{
                    String col1 = rs.getString("products_id");
                    String col2 = rs.getString("company_name");
                    String col3 = rs.getString("model");
                    String col4 = rs.getString("dimension");
                    String col5 = Integer.toString(rs.getInt("pcs_per_box"));
                    String col6 = rs.getString("item_unit");
                    String col7 = Double.toString(rs.getDouble("purchase_price"));
                    String col8 = Double.toString(rs.getDouble("selling_price"));
                    data.addRow(new Object[]{col1, col2, col3, col4, col5, col6, col7, col8});
                }while(rs.next());
                table.setModel(data);
                rs.close();
            }

        }catch(Exception ex){
            System.out.println("No database connection"+ex);
            NoConnection no = new NoConnection();
            RakibsTraders.popUp(no);
        }
    }

    //custom variable
    private JTable table = new JTable();
    private JFrame caller;
    //end of custom variable
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGO;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JTextField jTextFieldSearchProduct;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblProductList;
    private javax.swing.JScrollPane scrPaneTable;
    // End of variables declaration//GEN-END:variables
   
    private void setIcon(){
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/Icons/Icon.png")).getImage());
    }

    @Override
    public void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            caller.setEnabled(true);
            dispose();
        }
    }
    
    
    public void setCaller(JFrame frame){
        this.caller = frame;
    }
}
